version: '3'
services:
  db:
    image: rethinkdb:latest
    ports:  
      - "38080:8080"
  web:
    image: node:alpine    
    volumes:
      - ./startup:/usr/startup
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NPM_PROXY_CACHE=${MINIENV_NPM_PROXY_CACHE}
    command: /usr/startup/startup.sh
    ports:
      - "33000:3000"
    depends_on:
      - db
